M48
; DRILL file {KiCad 7.0.11-7.0.11~ubuntu22.04.1} date  5.09.2025 (пт) 11:14:01
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-09-05T11:14:01+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11-7.0.11~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.600
%
G90
G05
T1
X12.47Y14.39
X12.47Y8.61
M30
